In [8]:
# import pandas
import pandas as pd
from stats_can import StatsCan
sc = StatsCan(data_folder='../data_sources/raw_data/')

In [9]:
# retrieve table data for national MRA prices (1995 - 2022)
df = sc.table_to_df("18-10-0002-01")

In [10]:
# check dtypes
df.dtypes

REF_DATE         datetime64[ns]
GEO                    category
DGUID                  category
Products                 object
UOM                    category
UOM_ID                 category
SCALAR_FACTOR          category
SCALAR_ID              category
VECTOR                 category
COORDINATE             category
VALUE                   float64
STATUS                 category
SYMBOL                 category
TERMINATED             category
DECIMALS               category
dtype: object

In [11]:
# cast products column to string
df = df.astype({'Products':'string'})
df.dtypes

REF_DATE         datetime64[ns]
GEO                    category
DGUID                  category
Products         string[python]
UOM                    category
UOM_ID                 category
SCALAR_FACTOR          category
SCALAR_ID              category
VECTOR                 category
COORDINATE             category
VALUE                   float64
STATUS                 category
SYMBOL                 category
TERMINATED             category
DECIMALS               category
dtype: object

In [12]:
# create list of irrelevant products
irrelevant = ['Baby food', 'Infant formula', 'Deodorant', 'Toothpaste', 'Shampoo', 'Laundry detergent', 'Paper towels', 'tissue', 'Cigarettes', 'gasoline']

In [18]:
# remove rows where the product is irrelevant
for term in irrelevant:
    df = df[~df.Products.str.contains(term)]

df

,REF_DATE,GEO,DGUID,Products,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1995-01-01,Canada,2016A000011124,"Round steak, 1 kilogram",Dollars,81,units,0,v735165,1.1,10.17,NaN,NaN,NaN,2
1,1995-01-01,Canada,2016A000011124,"Sirloin steak, 1 kilogram",Dollars,81,units,0,v735176,1.2,11.25,NaN,NaN,NaN,2
2,1995-01-01,Canada,2016A000011124,"Prime rib roast, 1 kilogram",Dollars,81,units,0,v735187,1.3,12.08,NaN,NaN,NaN,2
3,1995-01-01,Canada,2016A000011124,"Blade roast, 1 kilogram",Dollars,81,units,0,v735198,1.4,7.23,NaN,NaN,NaN,2
4,1995-01-01,Canada,2016A000011124,"Stewing beef, 1 kilogram",Dollars,81,units,0,v735209,1.5,7.12,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18502,2022-02-01,Canada,2016A000011124,"Coffee, instant, 200 grams",Dollars,81,units,0,v735202,1.43,7.10,NaN,NaN,NaN,2
18503,2022-02-01,Canada,2016A000011124,Tea (72 bags),Dollars,81,units,0,v735203,1.44,4.49,NaN,NaN,NaN,2
18504,2022-02-01,Canada,2016A000011124,"Cooking or salad oil, 1 litre",Dollars,81,units,0,v735204,1.45,4.45,NaN,NaN,NaN,2
18505,2022-02-01,Canada,2016A000011124,"Soup, canned, 284 millilitres",Dollars,81,units,0,v735205,1.46,1.28,NaN,NaN,NaN,2
18507,2022-02-01,Canada,2016A000011124,"Peanut butter, 500 grams",Dollars,81,units,0,v735207,1.48,2.89,NaN,NaN,NaN,2

In [29]:
df1 = df[['REF_DATE', 'GEO', 'Products', 'VECTOR', 'VALUE']]
df1.rename(columns={'REF_DATE': 'date', 'GEO':'location', 'VALUE': 'price', 'Products': 'product', 'VECTOR': 'vectorid'}, inplace=True)

C:\Users\maddy\AppData\Local\Temp\ipykernel_15232\3656933377.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'REF_DATE': 'date', 'GEO':'location', 'VALUE': 'price', 'Products': 'product', 'VECTOR': 'vectorid'}, inplace=True)

In [32]:
df2 = pd.concat([df1, df1['product'].str.rsplit(',', n=1, expand=True)], axis=1).drop('product', axis=1)
df2

,date,location,vectorid,price,0,1
0,1995-01-01,Canada,v735165,10.17,Round steak,1 kilogram
1,1995-01-01,Canada,v735176,11.25,Sirloin steak,1 kilogram
2,1995-01-01,Canada,v735187,12.08,Prime rib roast,1 kilogram
3,1995-01-01,Canada,v735198,7.23,Blade roast,1 kilogram
4,1995-01-01,Canada,v735209,7.12,Stewing beef,1 kilogram
...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,"Coffee, instant",200 grams
18503,2022-02-01,Canada,v735203,4.49,Tea (72 bags),<NA>
18504,2022-02-01,Canada,v735204,4.45,Cooking or salad oil,1 litre
18505,2022-02-01,Canada,v735205,1.28,"Soup, canned",284 millilitres
18507,2022-02-01,Canada,v735207,2.89,Peanut butter,500 grams

In [33]:
# rename columns 
df2.rename(columns={0: 'product', 1: 'unit'}, inplace=True)
df2

,date,location,vectorid,price,product,unit
0,1995-01-01,Canada,v735165,10.17,Round steak,1 kilogram
1,1995-01-01,Canada,v735176,11.25,Sirloin steak,1 kilogram
2,1995-01-01,Canada,v735187,12.08,Prime rib roast,1 kilogram
3,1995-01-01,Canada,v735198,7.23,Blade roast,1 kilogram
4,1995-01-01,Canada,v735209,7.12,Stewing beef,1 kilogram
...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,"Coffee, instant",200 grams
18503,2022-02-01,Canada,v735203,4.49,Tea (72 bags),<NA>
18504,2022-02-01,Canada,v735204,4.45,Cooking or salad oil,1 litre
18505,2022-02-01,Canada,v735205,1.28,"Soup, canned",284 millilitres
18507,2022-02-01,Canada,v735207,2.89,Peanut butter,500 grams

In [34]:
df3 = pd.concat([df2, df2['product'].str.split('(', expand=True)], axis=1).drop('product', axis=1)
df3

,date,location,vectorid,price,unit,0,1
0,1995-01-01,Canada,v735165,10.17,1 kilogram,Round steak,<NA>
1,1995-01-01,Canada,v735176,11.25,1 kilogram,Sirloin steak,<NA>
2,1995-01-01,Canada,v735187,12.08,1 kilogram,Prime rib roast,<NA>
3,1995-01-01,Canada,v735198,7.23,1 kilogram,Blade roast,<NA>
4,1995-01-01,Canada,v735209,7.12,1 kilogram,Stewing beef,<NA>
...,...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,200 grams,"Coffee, instant",<NA>
18503,2022-02-01,Canada,v735203,4.49,<NA>,Tea,72 bags)
18504,2022-02-01,Canada,v735204,4.45,1 litre,Cooking or salad oil,<NA>
18505,2022-02-01,Canada,v735205,1.28,284 millilitres,"Soup, canned",<NA>
18507,2022-02-01,Canada,v735207,2.89,500 grams,Peanut butter,<NA>

In [35]:
# remove ")" from "20 bags)"
df3[1] = df3[1].str.replace(")", "")
df3[df3[1].notna()]

            date location vectorid  price  unit     0        1
43    1995-01-01   Canada  v735203   2.64  <NA>  Tea   72 bags
102   1995-02-01   Canada  v735203   2.66  <NA>  Tea   72 bags
161   1995-03-01   Canada  v735203   2.63  <NA>  Tea   72 bags
220   1995-04-01   Canada  v735203   2.61  <NA>  Tea   72 bags
279   1995-05-01   Canada  v735203   2.67  <NA>  Tea   72 bags
...          ...      ...      ...    ...   ...   ...      ...
18295 2021-10-01   Canada  v735203   4.29  <NA>  Tea   72 bags
18347 2021-11-01   Canada  v735203   4.27  <NA>  Tea   72 bags
18399 2021-12-01   Canada  v735203   4.31  <NA>  Tea   72 bags
18451 2022-01-01   Canada  v735203   4.45  <NA>  Tea   72 bags
18503 2022-02-01   Canada  v735203   4.49  <NA>  Tea   72 bags

[326 rows x 7 columns]

In [36]:
# fill null unit values with values split based on "(" delimiter
df3['unit'] = df3['unit'].fillna(df3[1])
df3

,date,location,vectorid,price,unit,0,1
0,1995-01-01,Canada,v735165,10.17,1 kilogram,Round steak,<NA>
1,1995-01-01,Canada,v735176,11.25,1 kilogram,Sirloin steak,<NA>
2,1995-01-01,Canada,v735187,12.08,1 kilogram,Prime rib roast,<NA>
3,1995-01-01,Canada,v735198,7.23,1 kilogram,Blade roast,<NA>
4,1995-01-01,Canada,v735209,7.12,1 kilogram,Stewing beef,<NA>
...,...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,200 grams,"Coffee, instant",<NA>
18503,2022-02-01,Canada,v735203,4.49,72 bags,Tea,72 bags
18504,2022-02-01,Canada,v735204,4.45,1 litre,Cooking or salad oil,<NA>
18505,2022-02-01,Canada,v735205,1.28,284 millilitres,"Soup, canned",<NA>
18507,2022-02-01,Canada,v735207,2.89,500 grams,Peanut butter,<NA>

In [37]:
# drop split column
df3.drop(1, axis=1, inplace=True)
df3

,date,location,vectorid,price,unit,0
0,1995-01-01,Canada,v735165,10.17,1 kilogram,Round steak
1,1995-01-01,Canada,v735176,11.25,1 kilogram,Sirloin steak
2,1995-01-01,Canada,v735187,12.08,1 kilogram,Prime rib roast
3,1995-01-01,Canada,v735198,7.23,1 kilogram,Blade roast
4,1995-01-01,Canada,v735209,7.12,1 kilogram,Stewing beef
...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,200 grams,"Coffee, instant"
18503,2022-02-01,Canada,v735203,4.49,72 bags,Tea
18504,2022-02-01,Canada,v735204,4.45,1 litre,Cooking or salad oil
18505,2022-02-01,Canada,v735205,1.28,284 millilitres,"Soup, canned"
18507,2022-02-01,Canada,v735207,2.89,500 grams,Peanut butter

In [38]:
# rename product column
df3.rename(columns={0:'product'}, inplace=True)
df3

,date,location,vectorid,price,unit,product
0,1995-01-01,Canada,v735165,10.17,1 kilogram,Round steak
1,1995-01-01,Canada,v735176,11.25,1 kilogram,Sirloin steak
2,1995-01-01,Canada,v735187,12.08,1 kilogram,Prime rib roast
3,1995-01-01,Canada,v735198,7.23,1 kilogram,Blade roast
4,1995-01-01,Canada,v735209,7.12,1 kilogram,Stewing beef
...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,200 grams,"Coffee, instant"
18503,2022-02-01,Canada,v735203,4.49,72 bags,Tea
18504,2022-02-01,Canada,v735204,4.45,1 litre,Cooking or salad oil
18505,2022-02-01,Canada,v735205,1.28,284 millilitres,"Soup, canned"
18507,2022-02-01,Canada,v735207,2.89,500 grams,Peanut butter

In [39]:
# remove leading and trailing whitespace from unit column
df3['unit'] = df3['unit'].replace(r"^ +| +$", r"", regex=True)

In [40]:
# split unit column into individual terms based on whitespace
df4 = pd.concat([df3, df3['unit'].str.split(' ', expand=True)], axis=1).drop('unit', axis=1)
df4

,date,location,vectorid,price,product,0,1
0,1995-01-01,Canada,v735165,10.17,Round steak,1,kilogram
1,1995-01-01,Canada,v735176,11.25,Sirloin steak,1,kilogram
2,1995-01-01,Canada,v735187,12.08,Prime rib roast,1,kilogram
3,1995-01-01,Canada,v735198,7.23,Blade roast,1,kilogram
4,1995-01-01,Canada,v735209,7.12,Stewing beef,1,kilogram
...,...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,"Coffee, instant",200,grams
18503,2022-02-01,Canada,v735203,4.49,Tea,72,bags
18504,2022-02-01,Canada,v735204,4.45,Cooking or salad oil,1,litre
18505,2022-02-01,Canada,v735205,1.28,"Soup, canned",284,millilitres
18507,2022-02-01,Canada,v735207,2.89,Peanut butter,500,grams

In [41]:
# rename columns 
df4.rename(columns={0: 'unit_quantity', 1: 'unit'}, inplace=True)
df4

,date,location,vectorid,price,product,unit_quantity,unit
0,1995-01-01,Canada,v735165,10.17,Round steak,1,kilogram
1,1995-01-01,Canada,v735176,11.25,Sirloin steak,1,kilogram
2,1995-01-01,Canada,v735187,12.08,Prime rib roast,1,kilogram
3,1995-01-01,Canada,v735198,7.23,Blade roast,1,kilogram
4,1995-01-01,Canada,v735209,7.12,Stewing beef,1,kilogram
...,...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,"Coffee, instant",200,grams
18503,2022-02-01,Canada,v735203,4.49,Tea,72,bags
18504,2022-02-01,Canada,v735204,4.45,Cooking or salad oil,1,litre
18505,2022-02-01,Canada,v735205,1.28,"Soup, canned",284,millilitres
18507,2022-02-01,Canada,v735207,2.89,Peanut butter,500,grams

In [42]:
# where unit_quantity is 'per', make unit_quantity = 1
df4['unit_quantity'] = df4['unit_quantity'].replace('per', '1')

In [43]:
# where unit_quantity is 'unit' and unit column is null, make unit_quantity = 1 and unit = each
df4['unit_quantity'] = df4['unit_quantity'].replace('unit', '1')
df4['unit'] = df4['unit'].fillna('each')
df4

,date,location,vectorid,price,product,unit_quantity,unit
0,1995-01-01,Canada,v735165,10.17,Round steak,1,kilogram
1,1995-01-01,Canada,v735176,11.25,Sirloin steak,1,kilogram
2,1995-01-01,Canada,v735187,12.08,Prime rib roast,1,kilogram
3,1995-01-01,Canada,v735198,7.23,Blade roast,1,kilogram
4,1995-01-01,Canada,v735209,7.12,Stewing beef,1,kilogram
...,...,...,...,...,...,...,...
18502,2022-02-01,Canada,v735202,7.10,"Coffee, instant",200,grams
18503,2022-02-01,Canada,v735203,4.49,Tea,72,bags
18504,2022-02-01,Canada,v735204,4.45,Cooking or salad oil,1,litre
18505,2022-02-01,Canada,v735205,1.28,"Soup, canned",284,millilitres
18507,2022-02-01,Canada,v735207,2.89,Peanut butter,500,grams

In [46]:
# redefine datatypes
df5 = df4.astype({'date': 'string', 'location': 'string', 'vectorid': 'string', 'product':'string', 'unit_quantity': 'float64', 'unit':'string'})

df5.dtypes

date             string[python]
location         string[python]
vectorid         string[python]
price                   float64
product          string[python]
unit_quantity           float64
unit             string[python]
dtype: object

In [47]:
# cast date column to datetime datatype
df5['date'] = pd.to_datetime(df5['date'])

In [68]:
def categorize_product(product):
    keywords = {
        'Frozen': ['frozen'],
        'Veg_Fruits': ['apples', 'oranges', 'bananas', 'pears', 'lemons', 'limes', 'grapes', 'grapefruits', 'cantaloupe', 'strawberries', 'avocado', 'potatoes', 'cabbage', 'carrots', 'onions', 'celery', 'cucumber', 'mushrooms', 'lettuce', 'broccoli', 'peppers', 'squash', 'salad greens', 'tomatoes'],
        'Grains': ['bread', 'flatbread', 'crackers', 'cookies', 'pasta', 'rice', 'macaroni', 'cereal', 'wheat', 'flour', 'corn flakes'],
        'Protein': ['beef', 'steak', 'rib', 'blade', 'chicken', 'pork', 'bacon', 'wieners', 'salmon', 'shrimp', 'tuna', 'eggs'],
        'Plant_based': ['meatless', 'soy milk', 'nut milk', 'beans', 'tofu'],
        'Other_foods': ['sugar', 'ketchup', 'peanut', 'mayonnaise', 'dried', 'dry', 'hummus', 'salsa', 'sauce', 'dressing', 'soup'],
        'Dairy': ['cream', 'butter', 'margarine', 'cheese', 'yogurt'],
        'Beverages': ['milk', 'juice', 'coffee', 'tea', 'fruit flavoured crystals', 'soft drinks', 'cola'],
        'Oils': ['oil'],
        'Unclassified': ['almonds', 'peanuts', 'sunflower']
    }
    for category, category_keywords in keywords.items():
        for keyword in category_keywords:
            if keyword.lower() in product.lower():
                return category
    
    return 'Others'

df5['category'] = df5['product'].apply(categorize_product)

In [73]:
# check that categories have been correctly assigned
df5[df5['category']=='Oils']['product'].unique()

<StringArray>
['Cooking or salad oil']
Length: 1, dtype: string

In [75]:
# save dataframe to .csv
df5.to_csv('../data_sources/clean_data/national_MRA_clean.csv', index=False)